[package]
name = "core_vimpeg"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
rust-embed = { workspace = true }
tokio = { workspace = true }
image = "0.24.7"
imageproc = "0.23.0"
ffmpeg-next = "7.1.0"
rusttype = "0.9.3"
bytes = "1.9.0"
