name: CI

on:
  push:
    branches: [ main, stable, next ]
  pull_request:
    branches: [ main, stable, next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
  #   env:
  #     DISPLAY: ":99.0"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@stable

  #     - name: Install ffmpeg
  #       run: sudo apt update && sudo apt install ffmpeg -y

  #     - name: Run tests
  #       run: cargo test --workspace

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          
      - name: Enforce formatting
        run: cargo fmt --check  

  # clippy:
  #   name: Clippy
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
  #   env:
  #     DISPLAY: ":99.0"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: clippy

  #     - name: Install ffmpeg
  #       run: sudo apt update && sudo apt install ffmpeg -y    
        
  #     - name: Linting
  #       run: cargo clippy -- -D warnings
